### ISSUE TITLE
allow us to use custom flags

### ISSUE THREAD

**Issue by meobu** [lohansimpson/x-feature-flags#10]
for example there is new flags but in the extension they are not updated. atleast allow users to input their own flags while u update the extension

**Comment by lohansimpson** [comment]
The visibility of this feature is controlled by a phased rollout of configuration flags. If your instance has not received the relevant flag, the option will not appear in the menu. Even if you manually add a custom flag, it will not take effect until the updated web application has been deployed to your environment.
