### ISSUE TITLE
Sidebar link does not scale with Twitter's font size adjustment

### ISSUE THREAD

**Issue by ghost** [lohansimpson/x-feature-flags#5]
<p>Twitter font scale</p>
<img width="40%" height="40%" alt="Twitter's font-size scaler on the smallest option." src="https://github.com/yaroslav-n/secret-twitter-features/assets/121842593/88e3d899-8c54-4c81-b3a8-66152b61f240">

<br><br>

<p>Sidebar link doesn't scale and looks out of place</p>
<img width="25%" height="25%" alt="Features sidebar link out of scale compared to the other links." src="https://github.com/yaroslav-n/secret-twitter-features/assets/121842593/fcea6190-fddf-486b-a033-07c268affe25">

**Comment by yaroslav-n** [comment]
Sorry, I completely missed that people post issues here. I'll see if I can fix this.
